# Test your FastAPI endpoints

GET http://127.0.0.1:8000/todos
Accept: application/json
###
POST http://127.0.0.1:8000/todos/{todo_id}
Accept: application/json
###
PUT http://127.0.0.1:8000/todos/{todo_id}
Accept: application/json
###
GET http://127.0.0.1:8000/todos/{todo_id}
Accept: application/json
###
DELETE http://127.0.0.1:8000/todos/{todo_id}
Accept: application/json

